var plat = [
{"id":82,"name":"Web browser"},
{"id":80,"name":"Neo Geo AES"},
{"id":79,"name":"Neo Geo MVS"},
{"id":78,"name":"Sega CD"},
{"id":77,"name":"Sharp X1"},
{"id":75,"name":"Apple II"},
{"id":74,"name":"Windows Phone"},
{"id":73,"name":"BlackBerry OS"},
{"id":72,"name":"Ouya"},
{"id":71,"name":"Commodore VIC-20"},
{"id":70,"name":"Vectrex"},
{"id":69,"name":"BBC Microcomputer System"},
{"id":68,"name":"ColecoVision"},
{"id":67,"name":"Intellivision"},
{"id":66,"name":"Atari 5200"},
{"id":65,"name":"Atari 8-bit"},
{"id":64,"name":"Sega Master System"},
{"id":63,"name":"Atari ST/STE"},
{"id":62,"name":"Atari Jaguar"},
{"id":61,"name":"Atari Lynx"},
{"id":60,"name":"Atari 7800"},
{"id":59,"name":"Atari 2600"},
{"id":58,"name":"Super Famicom"},
{"id":57,"name":"WonderSwan"},
{"id":56,"name":"WiiWare"},
{"id":55,"name":"Mobile"},
{"id":53,"name":"MSX2"},
{"id":52,"name":"Arcade"},
{"id":51,"name":"Family Computer Disk System"},
{"id":50,"name":"3DO Interactive Multiplayer"},
{"id":49,"name":"Xbox One"},
{"id":48,"name":"PlayStation 4"},
{"id":47,"name":"Virtual Console (Nintendo)"},
{"id":46,"name":"PlayStation Vita"},
{"id":45,"name":"PlayStation Network"},
{"id":44,"name":"Tapwave Zodiac"},
{"id":42,"name":"N-Gage"},
{"id":41,"name":"Wii U"},
{"id":39,"name":"iOS"},
{"id":38,"name":"PlayStation Portable"},
{"id":37,"name":"Nintendo 3DS"},
{"id":36,"name":"Xbox Live Arcade"},
{"id":35,"name":"Sega Game Gear"},
{"id":34,"name":"Android"},
{"id":33,"name":"Game Boy"},
{"id":32,"name":"Sega Saturn"},
{"id":30,"name":"Sega 32X"},
{"id":29,"name":"Sega Mega Drive/Genesis"},
{"id":27,"name":"MSX"},
{"id":26,"name":"ZX Spectrum"},
{"id":25,"name":"Amstrad CPC"},
{"id":24,"name":"Game Boy Advance"},
{"id":23,"name":"Dreamcast"},
{"id":22,"name":"Game Boy Color"},
{"id":21,"name":"Nintendo GameCube"},
{"id":20,"name":"Nintendo DS"},
{"id":19,"name":"Super Nintendo Entertainment System (SNES)"},
{"id":18,"name":"Nintendo Entertainment System (NES)"},
{"id":16,"name":"Amiga"},
{"id":15,"name":"Commodore C64/128"},
{"id":14,"name":"Mac"},
{"id":13,"name":"PC DOS"},
{"id":12,"name":"Xbox 360"},
{"id":11,"name":"Xbox"},
{"id":9,"name":"PlayStation 3"},
{"id":8,"name":"PlayStation 2"},
{"id":7,"name":"PlayStation"},
{"id":6,"name":"PC (Microsoft Windows)"},
{"id":5,"name":"Wii"},
{"id":4,"name":"Nintendo 64"},
{"id":3,"name":"Linux"},
{"id":130,"name":"Nintendo Switch"},
{"id":134,"name":"Acorn Electron"},
{"id":133,"name":"Philips Videopac G7000"},
{"id":132,"name":"Amazon Fire TV"},
{"id":131,"name":"Nintendo PlayStation"},
{"id":129,"name":"Texas Instruments TI-99"},
{"id":128,"name":"PC Engine SuperGrafx"},
{"id":127,"name":"Fairchild Channel F"},
{"id":126,"name":"TRS-80"},
{"id":125,"name":"PC-8801"},
{"id":124,"name":"SwanCrystal"},
{"id":123,"name":"WonderSwan Color"},
{"id":122,"name":"Nuon"},
{"id":121,"name":"Sharp X68000"},
{"id":120,"name":"Neo Geo Pocket Color"},
{"id":119,"name":"Neo Geo Pocket"},
{"id":118,"name":"FM Towns"},
{"id":117,"name":"Philips CD-i"},
{"id":116,"name":"Acorn Archimedes"},
{"id":115,"name":"Apple IIGS"},
{"id":114,"name":"Amiga CD32"},
{"id":113,"name":"OnLive Game System"},
{"id":112,"name":"Microcomputer"},
{"id":111,"name":"Imlac PDS-1"},
{"id":110,"name":"PLATO"},
{"id":109,"name":"CDC Cyber 70"},
{"id":108,"name":"PDP-11"},
{"id":107,"name":"Call-A-Computer time-shared mainframe computer system"},
{"id":106,"name":"SDS Sigma 7"},
{"id":105,"name":"HP 3000"},
{"id":104,"name":"HP 2100"},
{"id":103,"name":"PDP-7"},
{"id":102,"name":"EDSAC"},
{"id":101,"name":"Ferranti Nimrod Computer"},
{"id":100,"name":"Analogue electronics"},
{"id":99,"name":"Family Computer"},
{"id":98,"name":"DEC GT40"},
{"id":97,"name":"PDP-8"},
{"id":96,"name":"PDP-10"},
{"id":95,"name":"PDP-1"},
{"id":94,"name":"Commodore Plus/4"},
{"id":93,"name":"Commodore 16"},
{"id":92,"name":"SteamOS"},
{"id":91,"name":"Bally Astrocade"},
{"id":90,"name":"Commodore PET"},
{"id":89,"name":"Microvision"},
{"id":88,"name":"Odyssey"},
{"id":87,"name":"Virtual Boy"},
{"id":86,"name":"TurboGrafx-16/PC Engine"},
{"id":85,"name":"Donner Model 30"},
{"id":84,"name":"SG-1000"}
];

var platforms = {};
plat.forEach(sys=>{platforms[sys.id] = sys.name});
